### ISSUE TITLE
Easy to find Module list

### ISSUE THREAD

**Issue by segraef** [Azure/Modules#26]
## Description

To ease the search for Modules, a Modules list needs to be developed in https://github.com/Azure/Modules/tree/main/arm to have an overview of all current Modules with direct links to their respective folders they're sitting in. It would be also nice to have an overview like this: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-services-resource-providers

**Comment by MrMCake** [comment]
Resolved with attached PR
