### ISSUE TITLE
Repository structure

### ISSUE THREAD

**Issue by segraef** [Azure/Modules#9]
## Description

For a solid library base concrete file and folder structures must be defined.

- Modules
  - Folder structure
    - Modules/
      ┣ ModuleName/
       ┣ deploy.bicep
       ┣ deploy.json
       ┣ parameters.json
       ┗ readme.md
  - Basic elements (templates, parameters, pipelines, workflows, ...)
  - Readme (deploy to Azure button, readme structure, ...)
  - Naming convention (deploy.json/deploy.bicep/...)

- Repository
  - Folder structure (Resource provider based)
     - Modules/
      ┣ Microsoft.Compute/
      ┃ ┣ VirtualMachines/
      ┃ ┃ ┣ deploy.bicep
      ┃ ┃ ┣ deploy.json
      ┃ ┃ ┣ parameters.json
      ┃ ┃ ┗ readme.md
      ┃ ┗ VirtualMachineScaleSets/
      ┃   ┣ deploy.bicep
      ┃   ┣ deploy.json
      ┃   ┣ linux.parameters.json
      ┃   ┣ readme.md
      ┃   ┗ windows.parameters.json
      ┣ Microsoft.Storage/
      ┃ ┗ StorageAccounts/
      ┃   ┣ deploy.bicep
      ┃   ┣ deploy.json
      ┃   ┣ parameters.json
      ┃   ┗ readme.md

**Comment by MrMCake** [comment]
@segraef I guess we can resolve this issue for now and open a new one if the current setup does not suit the needs

**Comment by ahmadabdalla** [comment]
@segraef Do we want to address the child resource from a specific resourceType? i.e. Microsoft.Network/virtualNetworks/**virtualNetworkPeerings**?

**Comment by MrMCake** [comment]
@ahmadabdalla Agreed. Right now we have example 'Parameters' in a dedicated folder in each service module. In rare cases they point to a specific use case, but it's not generally the case. However, it makes sense as long as we can maintain those files (in case the module has e.g. a breaking change)
